version: "3"
services:
  test:
    image: cundd/rest
    volumes:
      - .:/app
      # - /tmp/:/tmp/ # linking /tmp/ folder because PHPStorm stores its stuff there
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typo3
